import { customAlphabet } from 'nanoid';
import { Role } from '@prisma/client';

// Deliberately excludes 0/O and 1/I/L so a support agent reading an NDY ID
// aloud over the phone can't misplace a character.
const ALPHABET = '23456789ABCDEFGHJKMNPQRSTUVWXYZ';
const nanoid = customAlphabet(ALPHABET, 6);

/**
 * Public NDY ID type segment ("class"). FOUNDER role maps to FND by
 * default; every other role (including all internal admin/staff roles —
 * SUPER_ADMIN, DEVELOPER, FINANCE, SUPPORT, CONTENT, PARTNERS, AUDITOR —
 * and the plain USER role) displays as MBR, since none of those are a
 * customer-facing account tier. BIZ is a reserved tier for business/
 * organization accounts — no existing signup or role-change flow assigns
 * it yet; it's wired through everywhere a type is read/written so turning
 * it on later (e.g. a business-account signup flow) is a product decision,
 * not another system-wide migration.
 *
 * CEO/EXE/PRT/INV/DEV are the founding/leadership identity classes (see
 * the client's "NDY ID — Identity & Leadership Structure" spec). Unlike
 * FND/BIZ/MBR, these are never derived from Role — they only ever come
 * from User.ndyIdType being explicitly set (see ndyIdTypeForUser below),
 * because a person's Role (what they can do) and their ID class (their
 * permanent, historical relationship to the ecosystem) are deliberately
 * separate axes per the spec's "Identity is permanent. Roles can evolve."
 * principle. There is no signup flow that assigns these — they're
 * hand-assigned to specific people (see prisma/seed-founding-team.ts).
 */
export type NdyIdType = 'CEO' | 'FND' | 'EXE' | 'PRT' | 'INV' | 'DEV' | 'BIZ' | 'MBR';

const ASSIGNABLE_ONLY_VIA_OVERRIDE: ReadonlySet<NdyIdType> = new Set([
  'CEO',
  'EXE',
  'PRT',
  'INV',
  'DEV',
]);

/**
 * The role-derived default — unchanged behavior for every user who has no
 * explicit ndyIdType override.
 */
export function ndyIdTypeForRole(role: Role): NdyIdType {
  return role === Role.FOUNDER ? 'FND' : 'MBR';
}

/**
 * The actual type segment to display for a given user: their explicit
 * User.ndyIdType override if set (validated against the assignable set),
 * otherwise the same role-derived default as before. This is the function
 * every call site should use going forward — ndyIdTypeForRole alone is no
 * longer sufficient once CEO/EXE/PRT/INV/DEV exist, since those can never
 * come from a Role value.
 */
export function ndyIdTypeForUser(user: { ndyIdType?: string | null; role: Role }): NdyIdType {
  if (user.ndyIdType) {
    return user.ndyIdType as NdyIdType;
  }
  return ndyIdTypeForRole(user.role);
}

export function isOverrideOnlyNdyIdType(type: string): boolean {
  return ASSIGNABLE_ONLY_VIA_OVERRIDE.has(type as NdyIdType);
}

/**
 * The permanent, never-changing part of a user's identity — six characters,
 * generated once at signup. Never regenerated by a role/type change: per
 * the client's explicit requirement, upgrading a member to a business
 * account (or a founding member's professional title changing) changes
 * only the displayed Type segment, never this code.
 */
export function generateCoreId(): string {
  return nanoid();
}

/**
 * Zero-padded sequential "genesis number" core segment, e.g. "000001" —
 * used only for the small, manually-curated set of founding/leadership NDY
 * IDs (CEO/FND/EXE/PRT/INV/DEV), never for ordinary member signup (which
 * stays on generateCoreId()'s random, non-enumerable value — see
 * docs/founding-identities.md for why the two schemes deliberately
 * coexist). The caller is responsible for picking the next unused number;
 * this just formats it consistently.
 */
export function formatGenesisCoreId(sequence: number): string {
  if (!Number.isInteger(sequence) || sequence < 1) {
    throw new Error(`Genesis sequence must be a positive integer, got ${sequence}`);
  }
  return String(sequence).padStart(6, '0');
}

/**
 * Builds the public-facing NDY ID string, e.g. "NDY-FND-4F82XK". This is
 * what's stored in User.ndyId and shown everywhere — there's no separate
 * "core id" column; the type segment is re-derived from the user's current
 * role/status on every read via this function rather than cached, so a
 * role change takes effect immediately without a data migration.
 */
export function formatNdyId(coreId: string, type: NdyIdType): string {
  return `NDY-${type}-${coreId}`;
}

/**
 * Splits a formatted NDY ID back into its parts. Accepts both the current
 * NDY-TYPE-XXXXXX format (any of the full NdyIdType class set, including
 * the founding/leadership classes and their zero-padded genesis numbers)
 * and the legacy pre-migration NDY-XXXXXX format (no type segment) so any
 * code path that still holds an old-format value (cached tokens, logs,
 * support tickets referencing an ID verbally) doesn't hard-crash — callers
 * needing the type should prefer reading it via ndyIdTypeForUser rather
 * than parsing it back out of the string.
 */
export function parseNdyId(
  ndyId: string,
): { type: NdyIdType | null; coreId: string } | null {
  const withType = /^NDY-(CEO|FND|EXE|PRT|INV|DEV|BIZ|MBR)-([A-Z0-9]{6})$/.exec(ndyId);
  if (withType) {
    return { type: withType[1] as NdyIdType, coreId: withType[2] };
  }
  const legacy = /^NDY-([A-Z0-9]{6})$/.exec(ndyId);
  if (legacy) {
    return { type: null, coreId: legacy[1] };
  }
  return null;
}
