import { customAlphabet } from 'nanoid';
import { Role } from '@prisma/client';

// Deliberately excludes 0/O and 1/I/L so a support agent reading an NDY ID
// aloud over the phone can't misplace a character.
const ALPHABET = '23456789ABCDEFGHJKMNPQRSTUVWXYZ';
const nanoid = customAlphabet(ALPHABET, 6);

/**
 * Public NDY ID type segment. FOUNDER maps to FND; every other role
 * (including all internal admin/staff roles — SUPER_ADMIN, DEVELOPER,
 * FINANCE, SUPPORT, CONTENT, PARTNERS, AUDITOR — and the plain USER role)
 * displays as MBR, since none of those are a customer-facing account tier.
 * BIZ is a reserved third tier for business/organization accounts — no
 * existing signup or role-change flow assigns it yet; it's wired through
 * everywhere a type is read/written so turning it on later (e.g. a
 * business-account signup flow) is a product decision, not another
 * system-wide migration.
 */
export type NdyIdType = 'FND' | 'BIZ' | 'MBR';

export function ndyIdTypeForRole(role: Role): NdyIdType {
  return role === Role.FOUNDER ? 'FND' : 'MBR';
}

/**
 * The permanent, never-changing part of a user's identity — six characters,
 * generated once at signup. Never regenerated by a role/type change: per
 * the client's explicit requirement, upgrading a member to a business
 * account changes only the displayed Type segment, never this code.
 */
export function generateCoreId(): string {
  return nanoid();
}

/**
 * Builds the public-facing NDY ID string, e.g. "NDY-FND-4F82XK". This is
 * what's stored in User.ndyId and shown everywhere — there's no separate
 * "core id" column; the type segment is re-derived from the user's current
 * role/status on every read via this function rather than cached, so a
 * role change takes effect immediately without a data migration.
 */
export function formatNdyId(coreId: string, type: NdyIdType): string {
  return `NDY-${type}-${coreId}`;
}

/**
 * Splits a formatted NDY ID back into its parts. Accepts both the current
 * NDY-TYPE-XXXXXX format and the legacy pre-migration NDY-XXXXXX format (no
 * type segment) so any code path that still holds an old-format value
 * (cached tokens, logs, support tickets referencing an ID verbally) doesn't
 * hard-crash — callers needing the type should prefer reading it from the
 * user's role directly via ndyIdTypeForRole rather than parsing it back out
 * of the string.
 */
export function parseNdyId(
  ndyId: string,
): { type: NdyIdType | null; coreId: string } | null {
  const withType = /^NDY-(FND|BIZ|MBR)-([A-Z0-9]{6})$/.exec(ndyId);
  if (withType) {
    return { type: withType[1] as NdyIdType, coreId: withType[2] };
  }
  const legacy = /^NDY-([A-Z0-9]{6})$/.exec(ndyId);
  if (legacy) {
    return { type: null, coreId: legacy[1] };
  }
  return null;
}
