"use client";

import { Mail, Calendar, CheckSquare, Bell } from "lucide-react";
import { useAuth } from "@/lib/auth-context";
import { useNdyspaceNotificationsList } from "@/lib/ndyspace-hooks";
import {
  markNdyspaceNotificationRead,
  markAllNdyspaceNotificationsRead,
  type NdyspaceNotification,
} from "@/lib/ndyspace-api";

const TYPE_ICON: Record<NdyspaceNotification["type"], typeof Bell> = {
  MAIL: Mail,
  CALENDAR: Calendar,
  TASK: CheckSquare,
  SYSTEM: Bell,
};

function relativeTime(iso: string): string {
  const diffMs = Date.now() - new Date(iso).getTime();
  const mins = Math.round(diffMs / 60000);
  if (mins < 1) return "just now";
  if (mins < 60) return `${mins}m ago`;
  const hours = Math.round(mins / 60);
  if (hours < 24) return `${hours}h ago`;
  const days = Math.round(hours / 24);
  return `${days}d ago`;
}

export default function NdyspaceNotificationsPage() {
  const { auth } = useAuth();
  const { data: notifications, error, loading, refetch } = useNdyspaceNotificationsList();

  if (auth.status !== "authenticated") return null;

  async function handleMarkRead(id: string) {
    await markNdyspaceNotificationRead(id);
    refetch();
  }

  async function handleMarkAllRead() {
    await markAllNdyspaceNotificationsRead();
    refetch();
  }

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <h1 className="text-2xl font-semibold">Notifications</h1>
          <p className="mt-1 text-sm text-foreground-muted">
            Generated by NDYSPACE modules (mail, calendar, tasks) as things happen.
          </p>
        </div>
        <button
          onClick={handleMarkAllRead}
          className="rounded-md border border-border px-3 py-1.5 text-xs hover:bg-surface-2"
        >
          Mark all read
        </button>
      </div>

      {error && <p className="text-sm text-critical">{error}</p>}

      <div className="rounded-lg border border-border bg-surface">
        {loading && !notifications ? (
          <p className="p-5 text-sm text-foreground-muted">Loading…</p>
        ) : notifications && notifications.length === 0 ? (
          <p className="p-5 text-sm text-foreground-muted">
            No notifications yet — you&apos;ll see activity from NDYMAIL, Calendar, and Tasks here.
          </p>
        ) : (
          <ul className="divide-y divide-border">
            {notifications?.map((n) => {
              const Icon = TYPE_ICON[n.type];
              return (
                <li
                  key={n.id}
                  onClick={() => !n.isRead && handleMarkRead(n.id)}
                  className={`flex cursor-pointer items-start gap-3 p-4 hover:bg-surface-2 ${!n.isRead ? "bg-accent/5" : ""}`}
                >
                  <span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-accent/15 text-accent">
                    <Icon size={15} strokeWidth={2} />
                  </span>
                  <div className="min-w-0 flex-1">
                    <p className={`text-sm ${!n.isRead ? "font-medium" : ""}`}>{n.message}</p>
                    <p className="text-xs text-foreground-muted">{relativeTime(n.createdAt)}</p>
                  </div>
                  {!n.isRead && <span className="mt-1.5 h-2 w-2 shrink-0 rounded-full bg-accent" />}
                </li>
              );
            })}
          </ul>
        )}
      </div>
    </div>
  );
}
